name: vector
channels:
  - conda-forge
  - defaults
dependencies:
  - arrow-cpp=4.0.1
  - bokeh
  - cryptography=3.4.7
  - holoviews=1.14.4
  - matplotlib=3.4.2
  - nodejs=16.4.1
  - numba=0.53.1
  - numpy=1.21.1
  - pandas=1.3.0
  - panel=0.11.3
  - param=1.11.1
  - parquet-cpp=1.5.1
  - pip=21.1.3
  - pyarrow=4.0.1
  - pyviz_comms=2.1.0
  - scikit-image=0.18.2
  - scikit-learn=0.24.2
  - scipy=1.7.0
  - pip:
    - en-core-web-sm==3.1.0
    - gensim==4.0.1
    - pyldavis==3.3.1
    - spacy==3.1.1
    - spacy-alignments==0.8.3
    - spacy-transformers==1.0.3
